### ISSUE TITLE
Junit XML test reports with multiple suites not supported

### ISSUE THREAD

**Issue by lefeverd** [nemerosa/ontrack-cli#18]
Hello,

I'm trying to validate the result of some tests with :

`./ontrack-cli --project myproject --branch mybranch --build 1234 --validation unit-tests junit --pattern "junit-test.xml"`

The Junit XML report was produced using pytest (with the `--junit-xml=<path>` flag).
It looks like the format it uses is not yet supported by the CLI, as it contains a `<testsuites>` root containing one or multiple `<testsuite>` and the CLI directly expects one `testsuite`.

Here is an example of an XML report :

```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="0" skipped="0" tests="13" time="0.354"
        timestamp="2024-01-27T13:40:41.596457" hostname="af4caa460457">
        <testcase classname="tests.unit.test_bookmark_serializer.TestBookmarkSerializer"
            name="test_bookmark_load" time="0.054" />
        <testcase classname="tests.unit.test_bookmark_serializer.TestBookmarkSerializer"
            name="test_bookmark_load_without_tld" time="0.001" />
        <testcase classname="tests.unit.test_bookmark_serializer.TestBookmarkSerializer"
            name="test_bookmark_load_invalid_url" time="0.001" />
        (...)
    </testsuite>
</testsuites>
```

I didn't find any official Junit XML spec, but is it something that could be supported by the CLI ?

Thanks !

**Comment by lefeverd** [comment]
If it's something you'd like to support, I can try to submit a PR.

**Comment by dcoraboeuf** [comment]
Yes, of course! You can submit any PR any time.

**Comment by dcoraboeuf** [comment]
There is a version 0.7.0 containing your pull request (#19).

Thanks for your contribution :)
